
name: Publish Website

on:
  push:
    branches:
      - main
    paths:
      - website/**
  workflow_dispatch:

jobs:
  publish-website:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install python Dependencies
        run: |
          pip install pybind11 nbclient nbformat ipykernel pandas numpy requests

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_CI }}
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
